<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Qiscus Chat</title>
    <link rel=stylesheet href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://s3-ap-southeast-1.amazonaws.com/qiscus-sdk/web/latest/qiscus-sdk.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans">
    <link rel="stylesheet" href="assets/css/login.css">
  </head>
  <body>
    <div class="wrapper">
      <h1 class="title">
        Qiscus Chat
      </h1>
      <img class="banner" src="assets/img/icon-logo-banner.svg" alt="Banner">
    </div>
    <script>
      var SDK_APP_ID = '<?= $CHAT_APP_ID; ?>';
    </script>
    <script src="https://unpkg.com/lodash@4.17.4/lodash.min.js"></script>
    <script src="https://unpkg.com/jquery@3.2.1/dist/jquery.js"></script>
    <script src="https://s3-ap-southeast-1.amazonaws.com/qiscus-sdk/web/latest/qiscus-sdk.js"></script>
    <script src="assets/js/md5.min.js"></script>
    <script src="assets/js/login.js"></script>
  </body>
</html>
